fixing listen snippet
RobertBrunhage/flutter-riverpod-snippets pull request #22
Opened 2022-06-17 03:23 UTC by GJJ2019

Before :
![Screenshot 2022-06-17 at 8 55 30 AM](https://user-images.githubusercontent.com/45948168/174218896-beb6f628-1dd0-4c8f-958f-dd50f327b373.png)

After: 
![Screenshot 2022-06-17 at 8 56 08 AM](https://user-images.githubusercontent.com/45948168/174218941-98e9de8a-4621-4612-af30-fe14ba97bd0c.png)

2022-06-17 05:07 UTC, RobertBrunhage commented
Thanks for the fix @GJJ2019!

Could you also update the `CHANGELOG.md` and `package.json` with the new version?

2022-06-17 05:34 UTC, GJJ2019 commented
done @RobertBrunhage

2022-06-17 05:59 UTC, RobertBrunhage requested changes
Just a minor detail

2022-06-17 05:59 UTC, RobertBrunhage commented on CHANGELOG.md
> +- fixing `listen` snippet
```suggestion
- Fix `listen` snippet to use previous & next
```

2022-06-18 06:41 UTC, RobertBrunhage approved these changes
Thanks for the PR!

2022-06-18 06:41 UTC, merged