code generator snippets
RobertBrunhage/flutter-riverpod-snippets pull request #26
Opened 2022-10-08 08:33 UTC by trejdych

Hello Robert,

I've added snippets for the new code generate syntax.

I think for the new syntax is more important to cover keep alive/autodispose than family.

I'll update readme when you accept snippets :)

sample gifs
![CleanShot 2022-10-08 at 10 18 27](https://user-images.githubusercontent.com/4202808/194698095-2716e61d-8483-4716-b5cb-0519467f722f.gif)
![CleanShot 2022-10-08 at 10 29 29](https://user-images.githubusercontent.com/4202808/194698185-ef37ad2a-5aa4-44a5-b0ea-206e077aab53.gif)

2022-10-09 17:06 UTC, pythonhubdev commented
Looks great

2022-10-11 05:30 UTC, RobertBrunhage commented
Looks good to me!

Feel free to update readme and the version!

2022-10-12 05:56 UTC, trejdych commented
Updated :)

2022-10-13 06:40 UTC, RobertBrunhage requested changes
One more small note:

Consider adding the snippets to the README as well!

2022-10-13 06:50 UTC, trejdych commented
Sorry, I don't understand. I did it in the last commit. Am I missing something?

2022-10-13 06:51 UTC, trejdych commented
ahh you mean CHANGELOG?

2022-10-13 07:04 UTC, trejdych commented
If you don't mind I would like to add Notifier and AsyncNotifier for the "old" syntax. I was focus on the code generator syntax only however it would cover all riverpod 2.0 changes. I can do it tonight.

2022-10-13 15:12 UTC, trejdych commented
Hello, I've fixed some indentations for code generator syntax and added few more snippets.

2022-10-29 21:19 UTC, leehack commented on snippets/code_generator.code-snippets
> +			"@Riverpod(keepAlive: true)",
Typo?
`@Rivderpod` -> `@riverpod`

2022-10-30 13:28 UTC, RobertBrunhage approved these changes

2022-10-30 13:29 UTC, RobertBrunhage commented
Sorry forgot this one, Looks good and will merge!

2022-10-30 13:29 UTC, merged

2022-10-30 14:57 UTC, trejdych commented
Thank you @RobertBrunhage

2022-10-30 15:31 UTC, RobertBrunhage commented
@trejdych seems like some of the new snippets wasn't added in the `package.json` if you get some time, would love to have a new PR with that!

2022-10-30 16:18 UTC, trejdych commented
Ahh. Sorry. I'll fix it tonight